### ISSUE TITLE
Error: Not found : cordova-plugin-ai-face

### ISSUE THREAD

**Issue by kikyo20** [MrBlack/cordova-plugin-ai-face#1]
##### not found?
![cordova-plugin-ai-face](https://user-images.githubusercontent.com/23587509/47058660-91063d80-d1f8-11e8-8657-1495484abcd3.png)

**Comment by MrBlack** [comment]
> ##### 未找到？
> ![科尔多瓦-插件-AI-面](https://user-images.githubusercontent.com/23587509/47058660-91063d80-d1f8-11e8-8657-1495484abcd3.png)

我只是上传到了github，没有上传到其余的插件库里面
